### ISSUE TITLE
Bandwidth 3-4x as expected

### ISSUE THREAD

**Issue by behinger** [intheon/stream_viewer#5]
I noticed that lsl_viewer needs 3-4x the bandwidth that I'd expect it to. E.g. lsl_recorder needs 2.6Mb/s, but the streamer 9-12Mb/s

More details on my setup:
https://github.com/sccn/labstreaminglayer/issues/122

**Comment by behinger** [comment]
okay some progress - for some reason stream_viewer wrote into the config multiple instantiations of the same stream (eegosport|0, eegosport|1) etc. - probably because it doesnt always recognize the stream (for whatever reasons).

I'm now down to 4-6mb

I think the issue is, that the stream_viewer uses lsl_status which polls the whole data in itself - so Bandwidth x2 is to be expected?

**Comment by cboulay** [comment]
Hi @behinger, I'll use this to answer a few comments / questions you raised here and elsewhere.

* `stream_viewer` is primarily intended to be a collection of modules and widgets that you use in a custom application.
* `lsl_viewer` is a mashup of examples using some of these modules and is not intended to be a highly performant ux-focused app.
* `lsl_status` uses the exact same data interface as the viewers, so yes it's pulling the data. If you don't want live updates as to the total throughput then this can be made much simpler. Even with live updates, it might be possible to use `samples_available` and `flush` only ... though I don't know if this actually prevents data transmission.

Given that `lsl_viewer` is more of an example than an app for the masses, I don't intend to make these changes. Instead, I encourage you to make your own app, using one or more of your favourite widgets.

> I'm assuming LSL is not as smart as to pull the package and then locally distribut it again

No. Each stream is a unique TCP connection. If you have multiple consumers on the same computer then you might benefit from using a single LSL inlet and re-sharing the data locally (e.g., this is how Blackrock's Central handles its 30 kHz 256+ ch data), but I wouldn't re-share as LSL streams because you're going to destroy your clock synchronization... so you have a lower limit of 1 for LabRecorder + at least 1 for other things.

**Comment by behinger** [comment]
Thanks for the answer! I did not perceive lsl_viewer as an example app but understand full, and indeed if I'd have time I'd program my own in the future :-)

Best, Benedikt
